# Generated by Django 4.2 on 2025-05-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender", models.CharField(max_length=100)),
                ("recipient", models.CharField(blank=True, max_length=100, null=True)),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_file", models.BooleanField(default=False)),
                ("file_url", models.CharField(blank=True, max_length=255, null=True)),
                ("is_group", models.BooleanField(default=True)),
            ],
        ),
    ]
