# Generated by Django 4.2 on 2025-05-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("image", "Image"),
                    ("video", "Video"),
                    ("audio", "Audio"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["uploaded_at"], name="chat_file_uploade_f14dc6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(fields=["name"], name="chat_group_name_c665ce_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["timestamp"], name="chat_messag_timesta_6494d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["sender", "recipient"], name="chat_messag_sender__941e05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["group"], name="chat_messag_group_i_3b3234_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["username"], name="chat_user_usernam_23b6f8_idx"
            ),
        ),
    ]
