# Generated by Django 4.2 on 2025-05-13 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_remove_message_is_file_remove_message_is_group_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="file",
            old_name="created_at",
            new_name="uploaded_at",
        ),
        migrations.RemoveField(
            model_name="group",
            name="invite_code",
        ),
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="file",
            name="file_type",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="file",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="chat.message",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="useractivity",
            name="details",
            field=models.JSONField(default=dict),
        ),
    ]
