# Generated by Django 5.2.1 on 2025-05-09 20:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_message_file_url_alter_user_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="file_url",
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
