# Generated by Django 5.2.1 on 2025-05-18 15:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_remove_user_last_seen_user_last_login_alter_group_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="last_login",
        ),
        migrations.AddField(
            model_name="user",
            name="last_seen",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
