# Generated by Django 5.2.1 on 2025-05-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_remove_user_last_login_user_last_seen_alter_group_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="last_seen",
        ),
        migrations.AddField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
