# Generated by Django 5.2.1 on 2025-05-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_remove_user_last_seen_user_last_login_alter_group_id"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["sender", "timestamp"], name="chat_messag_sender__b20cde_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["recipient", "timestamp"], name="chat_messag_recipie_f09335_idx"
            ),
        ),
    ]
