# Generated by Django 5.2.1 on 2025-05-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_message_chat_messag_sender__b20cde_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["file_type"], name="chat_file_file_ty_72678a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(
                fields=["creator"], name="chat_group_creator_11f8bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["group", "timestamp"], name="chat_messag_group_i_74a3f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_online"], name="chat_user_is_onli_abb16d_idx"
            ),
        ),
    ]
